# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
